/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "logRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_operation_1(log_request req, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOG_OPERATION,
		(xdrproc_t) xdr_log_request, (caddr_t) &req,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
