/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGRPC_H_RPCGEN
#define _LOGRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_USER_LENGTH 256
#define MAX_OPERATION_LENGTH 256
#define MAX_FILE_LENGTH 256

struct log_request {
	char *user;
	char *operation;
	char *file_name;
};
typedef struct log_request log_request;

#define LOGRPC_PROG 0x20000124
#define LOGRPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  enum clnt_stat log_operation_1(log_request , int *, CLIENT *);
extern  bool_t log_operation_1_svc(log_request , int *, struct svc_req *);
extern int logrpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  enum clnt_stat log_operation_1();
extern  bool_t log_operation_1_svc();
extern int logrpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_request (XDR *, log_request*);

#else /* K&R C */
extern bool_t xdr_log_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGRPC_H_RPCGEN */
