/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logRPC.h"

bool_t
xdr_log_request (XDR *xdrs, log_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, MAX_USER_LENGTH))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, MAX_OPERATION_LENGTH))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, MAX_FILE_LENGTH))
		 return FALSE;
	return TRUE;
}
